---
openapi: 3.0.3
info:
  version: 0.0.1
  title: Public API категорий товаров
  description: Public REST API проекта go-sample категорий товаров
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Andrey Nazarov