---
app:
  name: "Go Sample App"
  version: v0.0.0 # auto detection
  environment: local # dev, prod

debugging:
  debug: true
  unexpected_http_status: 418 # http.StatusTeapot
  error_caller:
    enable: true
    depth: 3
    show_func_name: true
    upper_bounds:
      - github.com/mondegor/go-sysmess/mrerr.(*ProtoAppError).New
      - github.com/mondegor/go-sysmess/mrerr.(*ProtoAppError).Wrap
      - github.com/mondegor/go-webcore/mrcore.PrepareError
      - github.com/mondegor/go-webcore/mrcore/mrcoreerr.(*ErrorHandler).Process
      - github.com/mondegor/go-webcore/mrlog/zerolog.(*eventAdapter).Err
      - github.com/mondegor/go-storage/mrpostgres.(*ConnAdapter).Query
      - github.com/mondegor/go-storage/mrpostgres.(*queryRows).Scan

logger:
  level: trace # debug, info, warn, error, fatal, trace
  json_format: false
  timestamp_format: TimeOnly # RFC3339, RFC3339Nano, DateTime, TimeOnly
  console_color: true

sentry:
  enable: false
  dsn: http://id@127.0.0.1:9980/1
  traces_sample_rate: 1.0
  flush_timeout: 2s

servers:
  rest_server:
    read_timeout: 5s
    write_timeout: 5s
    shutdown_timeout: 15s
    listen:
      bind_ip: 0.0.0.0
      port: 8080
  prometheus_server:
    read_timeout: 5s
    write_timeout: 5s
    shutdown_timeout: 15s
    listen:
      bind_ip: 0.0.0.0
      port: 8084

storage:
  type: postgres
  host: 127.0.0.1
  port: 5432
  username: user_pg
  password: 123456
  database: db_pg
  max_pool_size: 2
  timeout: 30s

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  timeout: 30s

file_system:
  dir_mode: 0775
  create_dirs: true # check and create if not exists

s3:
  host: 127.0.0.1
  port: 9000
  use_ssl: false
  username: admin # d4jrL7eXyKg7ZNdYdl2p
  password: 12345678 # qZkNDK1Hewb4GVEvzvZGRCVb5uU4ZCX9bKztlhvR
  create_buckets: true # check and create if not exists

file_providers:
  image_storage:
    name: imageStorage
    bucket_name: go-sample-img
  image_storage2:
    name: imageStorage2
    root_dir: "./img"

cors:
  allowed_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  allowed_headers:
    - Content-Type
    - Authorization
    - X-Correlation-Id
    - X-Idempotency-Key
  exposed_headers:
    - X-Correlation-Id
  allow_credentials: true

translation:
  dir_path: "./translate"
  lang_codes: # the first language is default
    - en_EN
    - ru_RU
  dictionaries:
    dir_path: "./translate/dict"
    list:
      - catalog/categories

app_sections:
  admin_api:
    privilege: apiAdm
    auth:
      secret: "The secret for symmetric security key"
      audience: "127.0.0.1:80"
  public_api:
    privilege: apiPublic
    auth:
      secret: "The secret for symmetric security key"
      audience: "127.0.0.1:80"

access_control:
  roles:
    dir_path: "./roles"
    file_type: yaml
    list: # the first role is the guest role
      - guests
      - administrators
  privileges:
    - apiAdm
    - apiPublic
  permissions:
    - modCatalogCategory
    - modCatalogProduct
    - modCatalogTrademark
    - modFileStation

modules_settings:
  general:
    page_size_max: 1000
    page_size_default: 50
  catalog_category:
    image:
      file_provider: imageStorage # file_providers.image_storage or image_storage2
  file_station:
    image_proxy:
      host: http://127.0.0.1:8080/
      base_url: /img/{{path}}
      file_provider: imageStorage # file_providers.image_storage or image_storage2

task_schedule:
  settings_reloader:
    caption: Settings reloader
    startup: true
    period: 15s
    timeout: 30s

mime_types:
  - ext: gif
    type: image/gif
  - ext: jpeg
    type: image/jpeg
  - ext: jpg
    type: image/jpeg
  - ext: png
    type: image/png