---
openapi: 3.0.3
info:
  version: v0.2.0
  title: Public API go-sample
  description: Public REST API проекта go-sample
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Andrey Nazarov