-- --------------------------------------------------------------------------------------------------

CREATE TABLE sample_catalog.trademarks (
    trademark_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_trademarks PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    trademark_caption character varying(64) NOT NULL,
    trademark_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

-- --------------------------------------------------------------------------------------------------

INSERT INTO sample_catalog.trademarks (trademark_id, tag_version, trademark_caption, trademark_status, created_at, updated_at, deleted_at)
VALUES
    (1, 1, 'Алёнка', 2/*ENABLED*/, '2023-01-01 12:10:59.981966', '2023-01-01 12:10:59.981966', NULL),
    (2, 1, 'Маша и Медведь', 3/*DISABLED*/, '2023-02-01 13:10:08.678538', '2023-02-01 13:10:08.678538', NULL),
    (3, 1, 'Юбилейное', 2/*ENABLED*/, '2023-03-01 14:10:16.078388', '2023-03-01 14:10:16.078388', NULL),
    (4, 1, 'Бабаевский', 2/*ENABLED*/, '2023-04-01 15:10:23.319733', '2023-04-01 15:10:23.319733', NULL),
    (5, 1, 'Кара-Кум', 1/*DRAFT*/, '2023-05-01 16:10:23.319733', '2023-05-01 16:10:23.319733', NULL),
    (6, 1, 'Мишка на Севере', 2/*ENABLED*/, '2023-06-01 17:10:14.319733', '2023-06-01 17:10:14.319733', NULL),
    (7, 1, 'Радуга ТВ', 2/*ENABLED*/, '2023-07-01 18:10:23.319733', '2023-07-01 18:10:23.319733', NULL),
    (8, 1, 'Ракета', 1/*DRAFT*/, '2023-08-01 19:10:45.319733', '2023-08-01 19:10:45.319733', NULL);

ALTER SEQUENCE sample_catalog.trademarks_trademark_id_seq RESTART WITH 9;