Catalog.Products.AdminAPI.Request.Path.ProductID:
  description: Идентификатор товара
  name: productId
  in: path
  required: true
  schema:
    type: integer
    # format: uint64
    minimum: 1
  example: 1000