FileStation.PublicAPI.Request.Path.FilePath:
  description: Относительный путь к файлу
  name: filePath
  in: path
  required: true
  schema:
    type: string
    minLength: 5
    maxLength: 128
  example: "category/item-name.jpg"