name: Audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './app/go.mod'

    - name: Download mods
      run: cd ./app && go mod download

    - name: Build
      run: cd ./app && go build -v ./...

    - name: Run go vet
      run: cd ./app && go vet ./...

    - name: Install staticcheck
      run: cd ./app && go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: cd ./app && staticcheck ./...

    - name: Run tests
      run: cd ./app && go test ./...