name: Audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.4'

    - name: Download mods
      run: cd ./app && go mod download

    - name: Build
      run: cd ./app && go build -v ./...

    - name: Run go vet
      run: cd ./app && go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: cd ./app && staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: cd ./app && golint ./...

    - name: Run tests
      run: cd ./app && go test -race -vet=off ./...